services:
  nextjs:
    build:
      context: .
      dockerfile: ./.config/Dockerfile
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - backend_network

  backend:
    image: node:alpine
    container_name: backend_app
    working_dir: /app
    volumes:
      - ./src/server/controller:/app
      - ./package.json:/app/package.json
    command: node server.js
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - backend_network

  websocket_worker:
    image: node:18-alpine
    container_name: websocket_worker
    working_dir: /app
    volumes:
      - ./src/server/controller:/app
      - ./package.json:/app/package.json
    command: node websocket.js
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3001:3001'
    depends_on:
      - redis
    networks:
      - backend_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend_network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./.config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - nextjs
      - websocket_worker
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
